project:
  type: website
  resources:
    - presentations
    - assets

# handle redirects from old blog
files:
  - assets/autoequipement-REL-ACFAS-2023.html
  - assets/open-source-tools-fabriqueREL2023.html

website:
  title: "Christopher Fuhrman"
  site-url: https://fuhrmanator.github.io/
  description: "Christopher Fuhrman, software developer and professor of software engineering."
  favicon: favicon.png
  open-graph: 
    locale: en_US
  twitter-card:
    creator: "@thefuhrmanator"
  comments:
    hypothesis:
      theme: clean

  navbar:
    right:
      - about.qmd
      - text: "Home"
        href: index.html
      # - text: "Papers"
      #   href: papers
      # - text: "Presentations"
      #   href: presentations
      - text: "Blog"
        href: blogging-allowed.html
      - icon: github
        href: https://github.com/fuhrmanator
      - icon: linkedin
        href: https://www.linkedin.com/in/fuhrmanator/
      - icon: twitter-x
        href: https://twitter.com/thefuhrmanator
      - icon: envelope
        href: mailto:christopher.fuhrman@etsmtl.ca
      - icon: rss
        href: index.xml
      - text: "⚰"
        href: monets.html
format:
  html:
    theme: journal
    css: styles.css
    highlight-style: github
    syntax-definitions: 
      - syntax-highlighters/smalltalk.xml

filters:
  - diagram
  
diagram:
  engine:
    plantuml:
      mime-type:
        image/svg+xml: true
        application/pdf: false

execute: 
  freeze: auto
