on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml graphviz


      - name: Quarto Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-extension: '.qmd'
          use-quiet-mode: "yes"
          config-file: "markdown-link-check-config.json"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
